
---
- hosts: kafkanodes
  # using `root` user the do all the work.
  remote_user: root
 
  tasks:
 
  - name: Starting kafka server on port 9092.
    raw: if [ `jps | grep Kafka | xargs | awk '{ print $1}'` ]; then kill -9 `jps | grep Kafka | xargs | awk '{ print $1}'`; fi;
    sudo: yes
    sudo_user: "{{ kafka_user }}"

  - name: Stop Kafka
    systemd: state=stopped name=kafka.service daemon_reload=yes

  - name: Remove Kafka Service File.
    command: rm /etc/systemd/system/kafka.service 
 
  - name: Remove Directories.
    command: rm -rf {{ common['soft_link_base_path'] }}/kafka {{ common['install_base_path'] }}/{{ kafka_version }} {{ kafka_data_store }}


- hosts: zookeepernodes
  remote_user: root
  tasks:

  - name: Stop Zookeeper
    command: sh {{ common['soft_link_base_path'] }}/zookeeper/bin/zkServer.sh stop
    sudo: yes
    sudo_user: "{{ zookeeper_user }}"

  - name: Stop ZooKeeper
    systemd: state=stopped name=zookeeper.service daemon_reload=yes

  - name: Remove ZooKeeper Service File.
    command: rm /etc/systemd/system/zookeeper.service 

  - name: Remove Zookeeper Directories.
    command: rm -rf {{ common['soft_link_base_path'] }}/zookeeper {{ common['install_base_path'] }}/{{ zookeeper_version }} {{ zookeeper_data_store }} {{ zookeeper_logging }}

